DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS NOTES;

CREATE TABLE ACCOUNT (ACCOUNT_NUMBER varchar(255), PIN varchar(255), BALANCE decimal(15,2), OVERDRAFT decimal(15,2), CONSTRAINT acct_pk PRIMARY KEY (ACCOUNT_NUMBER));
CREATE TABLE NOTES (NOTE_CATEGORY number(2), QUANTITY number(2), CONSTRAINT dispenser_pk PRIMARY KEY (NOTE_CATEGORY));